### ISSUE TITLE
Uncaught TypeError: Cannot read property 'keyIdentifier' of undefined

### ISSUE THREAD

**Issue by ganeshabrightscope** [bronson/vim-mode-next#10]
[Enter steps to reproduce below:]
1.  open a file with more than 1 line
2. try to delete or yank n lines/words etc like "10yy"

Error occurs immediately after pressing the number key

**Atom Version**: 1.0.13
**System**: Ubuntu Wily
**Thrown From**: [vim-mode-next](https://github.com/bronson/vim-mode-next) package, v0.57.2
### Stack Trace

Uncaught TypeError: Cannot read property 'keyIdentifier' of undefined

```
At /usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/helpers.js:345

TypeError: Cannot read property 'keyIdentifier' of undefined
  at keyForKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/helpers.js:345:26)
  at exports.keystrokeForKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/helpers.js:162:11)
  at KeymapManager.module.exports.KeymapManager.keystrokeForKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:385:14)
  at VimState.module.exports.VimState.repeatPrefix (/home/bhaskara/.atom/packages/vim-mode-next/lib/vim-state.coffee:615:33)
  at atom-text-editor.registerCommands.repeat-prefix (/home/bhaskara/.atom/packages/vim-mode-next/lib/vim-state.coffee:75:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:240:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:184:20)

```
### Commands

```
     -0:21.8.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 17x -0:21 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 17x -0:10.7.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:07.6.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:06.1.0 vim-mode:yank (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -0:03.3.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:00.6.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "projectHome": "/home/bhaskara/workspace/lantern",
    "audioBeep": false,
    "ignoredNames": [
      ".git",
      ".tox",
      ".pyc",
      ".idea",
      "node_modules",
      ".coverage",
      ".coveragerc",
      "python/.tox/*",
      "*.h",
      "*.c",
      "compiled",
      "*.css",
      "coffee/node_modules/*",
      ""
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ],
    "followSymlinks": false
  },
  "vim-mode-next": {}
}
```
### Installed Packages

``` coffee
# User
atom-jade, v0.3.0
atom-jinja2, v0.5.0
atom-material-syntax, v0.2.4
atom-material-ui, v0.6.1
autocomplete-python, v0.5.3
clipboard-plus, v0.5.1
editorconfig, v1.2.0
ex-mode, v0.7.0
file-icons, v1.6.9
git-blame, v0.4.5
language-gherkin, v1.0.2
language-jade, v0.6.2
linter, v1.5.2
linter-coffeelint, v1.1.0
linter-flake8, v1.6.1
symbol-gen, v1.0.0
symbols-tree-view, v0.10.0
tree-ignore, v0.2.6
vim-mode-clipboard-plus, v0.1.0
vim-mode-next, v0.57.2
vim-mode-visual-block, v0.2.13
vim-surround, v0.8.0

# Dev
No dev packages
```

**Comment by ganeshabrightscope** [comment]
https://github.com/atom/vim-mode/issues/863
