### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hiddenInputComponent' of null

### ISSUE THREAD

**Issue by gregmacfarlane** [bronson/vim-mode-next#13]
[Enter steps to reproduce below:]
1. Start vim search by hitting `/` in command mode
2. Completing the command with `[return]` or exiting with `[esc]`

**Atom Version**: 1.3.2
**System**: Mac OS X 10.11.2
**Thrown From**: [vim-mode-next](https://github.com/bronson/vim-mode-next) package, v0.57.5
### Stack Trace

Uncaught TypeError: Cannot read property 'hiddenInputComponent' of null

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:259

TypeError: Cannot read property 'hiddenInputComponent' of null
    at atom-text-editor.TextEditorElement.blurred (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:259:51)
    at HTMLInputElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor-element.js:235:26)
    at atom-pane.PaneElement.activated (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-element.js:113:19)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at Pane.module.exports.Pane.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:625:27)
    at vim-normal-mode-input.VimNormalModeInputElement.removePanel (/Users/Greg/.atom/packages/vim-mode-next/lib/view-models/vim-normal-mode-input-element.coffee:53:36)
    at vim-normal-mode-input.VimNormalModeInputElement.confirm (/Users/Greg/.atom/packages/vim-mode-next/lib/view-models/vim-normal-mode-input-element.coffee:43:6)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -1:03.2.0 core:move-down (input.hidden-input)
     -1:02.8.0 autocomplete-plus:confirm (input.hidden-input)
     -0:59.3.0 vim-mode:activate-normal-mode (input.hidden-input)
     -0:59 vim-mode:move-up (input.hidden-input)
     -0:58.8.0 vim-mode:insert-below-with-newline (input.hidden-input)
     -0:57.6.0 core:backspace (input.hidden-input)
     -0:56.3.0 vim-mode:activate-normal-mode (input.hidden-input)
  2x -0:56 vim-mode:delete (input.hidden-input)
     -0:54.3.0 vim-mode:insert-after-end-of-line (input.hidden-input)
     -0:53.9.0 vim-mode:move-left-insert (input.hidden-input)
 36x -0:49.3.0 blur (input.hidden-input)
     -0:06.0 vim-mode:search (input.hidden-input)
  3x -0:05.9.0 blur (input.hidden-input)
  6x -0:03.5.0 core:backspace (input.hidden-input)
     -0:02.0 core:confirm (input.hidden-input)
  3x -0:02.0 blur (input.hidden-input)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "solarized-light-syntax"
    ],
    "disabledPackages": [
      "linter-lintr",
      "linter-chktex",
      "markdown-preview",
      "vim-mode",
      "Hydrogen"
    ],
    "openEmptyEditorOnStart": false
  }
}
```
### Installed Packages

``` coffee
# User
atom-terminal-panel, v4.4.4
auto-update-packages, v1.0.0
browser-plus, v0.0.54
file-watcher, v0.4.0
git-diff-details, v0.21.0
git-log, v0.4.1
language-knitr, v0.2.0
language-latex, v0.6.1
language-r, v0.4.0
language-x86, v0.1.0
latex, v0.28.2
latexer, v0.2.7
line-ending-converter, v1.3.2
linter, v1.11.3
markdown-preview-plus, v2.2.2
minimap, v4.19.0
minimap-git-diff, v4.1.8
pdf-view, v0.37.0
tablr, v0.9.0
tree-view-git-status, v0.2.2
vim-mode-next, v0.57.5
vim-mode-visual-block, v0.2.14

# Dev
No dev packages
```

**Comment by bronson** [comment]
Hi, thanks for the report!  However, I'm not maintaining vim-mode-next anymore...  I'm using vim-mode-plus and contributing where I can.

I'd guess this is backtrace is due to recent Atom changes.  Looks like the bit rot is starting to set in.  :(

**Comment by gregmacfarlane** [comment]
Okay, I will move to the maintained package.

**Comment by bronson** [comment]
Sorry, I wish there was a better way to notify users when a package is EOLed.

vim-mode-plus is getting really impressive...  Not much chance for vim-mode-next to catch up.
