### ISSUE TITLE
Failed to load the vim-mode-next package

### ISSUE THREAD

**Issue by Antonio-Ropero-Muela** [bronson/vim-mode-next#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.0
**System**: Unknown Windows Version
**Thrown From**: [vim-mode-next](https://github.com/bronson/vim-mode-next) package, v0.54.12
### Stack Trace

Failed to load the vim-mode-next package

```
At Failed to execute 'registerElement' on 'Document': Registration failed for type 'vim-command-mode-input'. A type with that name is already registered.

Error: Failed to execute 'registerElement' on 'Document': Registration failed for type 'vim-command-mode-input'. A type with that name is already registered.
    at Error (native)
    at Object.<anonymous> (C:\Users\Antonio Ropero\.atom\packages\vim-mode-next\lib\view-models\vim-command-mode-input-element.coffee:89:29)
    at Object.<anonymous> (C:\Users\Antonio Ropero\.atom\packages\vim-mode-next\lib\view-models\vim-command-mode-input-element.coffee:94:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (C:\Users\Antonio Ropero\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (C:\Users\Antonio Ropero\.atom\packages\vim-mode-next\lib\view-models\view-model.coffee:4:32)
    at Object.<anonymous> (C:\Users\Antonio Ropero\.atom\packages\vim-mode-next\lib\view-models\view-model.coffee:59:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (C:\Users\Antonio Ropero\AppData\Local\atom\app-1.0.0\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```
### Commands

```
     -1:33.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -1:14.4.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.0
angularjs-boilerplate-snippets, v0.3.1
angularjs-snippets, v0.10.18
angularjs-styleguide-snippets, v0.7.2
atom-django, v0.3.0
autocomplete-modules, v1.0.0
autocomplete-plus-python-jedi, v0.3.6
autocomplete-python, v0.5.1
color-picker, v2.0.9
csslint, v1.1.3
django-atom, v0.2.3
django-templates, v0.5.0
editor-stats, v0.17.0
editorconfig, v1.0.1
emmet, v2.3.12
file-icons, v1.5.8
highlight-line, v0.11.0
highlight-selected, v0.10.1
javascript-snippets, v1.0.0
jshint, v1.3.9
language-coffee-script-angular, v2.2.0
language-django, v0.1.1
language-mongodb, v0.2.0
minimap, v4.10.2
minimap-highlight-selected, v4.3.0
node-debugger, vundefined
node-on-fire, v0.1.0
save-session, v0.15.6
vim-mode, v0.54.0
vim-mode-next, v0.54.12

# Dev
No dev packages
```

**Comment by bronson** [comment]
Hi, great to see it being used on windows!

Here's the issue:

```
vim-mode, v0.54.0
vim-mode-next, v0.54.12
```

You need to disable vim-mode (or vim-mode-next) and restart Atom...  vim-mode and vim-mode-next step on each others' toes.

**Comment by Antonio-Ropero-Muela** [comment]
thank you

**Comment by bronson** [comment]
Happy to.  Closing this for now...  I'll reopen it if it's tripping up other people too.
