### ISSUE TITLE
pr782 fails in vim-mode-next

### ISSUE THREAD

**Issue by bronson** [bronson/vim-mode-next#7]
@jacekkopecky, ran into an issue merging https://github.com/atom/vim-mode/pull/782 into vim-mode-next:

On this branch: https://github.com/bronson/vim-mode-next/tree/ready-pr782-probs

The following two tests fail:

```
...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F......

VimState
  visual-mode
    the o keybinding
      it harmonizes selection directions
        Expected [ { row : 0, column : 6 }, { row : 0, column : 13 } ] to equal [ [ 0, 6 ], [ 0, 12 ] ].
          at [object Object].<anonymous> (/Users/bronson/vim-mode-next/spec/vim-state-spec.coffee:377:51)
          at _fulfilled (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:794:54)
          at self.promiseDispatch.done (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:823:30)
          at Promise.promise.promiseDispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:756:13)
          at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:564:44
          at flush (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:110:17)
          at process._tickCallback (node.js:357:13)
        Expected [ { row : 0, column : 4 }, { row : 0, column : 12 } ] to equal [ [ 0, 6 ], [ 0, 13 ] ].
          at [object Object].<anonymous> (/Users/bronson/vim-mode-next/spec/vim-state-spec.coffee:388:51)
          at _fulfilled (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:794:54)
          at self.promiseDispatch.done (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:823:30)
          at Promise.promise.promiseDispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:756:13)
          at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:564:44
          at flush (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:110:17)
          at process._tickCallback (node.js:357:13)


Finished in 10.69 seconds
546 tests, 1174 assertions, 2 failures, 0 skipped

Tests failed
```

I haven't looked too hard yet, hoping you'd know offhand...?

**Comment by bronson** [comment]
I figured the conflicting pr would be https://github.com/atom/vim-mode/pull/770 but nope!  They work fine together.

**Comment by jacekkopecky** [comment]
It was actually atom/vim-mode#782 I think (or atom/vim-mode#783); here's how I resolved the merge in the spec:

```
      it "harmonizes selection directions", ->
        editor.setCursorBufferPosition([0, 0])
        keydown("e")
        keydown("e")
        editor.addCursorAtBufferPosition([0, Infinity])
        keydown("h")
        keydown("h")

        expect(editor.getSelectedBufferRanges()).toEqual([
          [[0, 0], [0, 5]],
          [[0, 11], [0, 13]]
        ])
        expect(editor.getCursorBufferPositions()).toEqual([
          [0, 5]
          [0, 11]
        ])

        keydown("o")

        expect(editor.getSelectedBufferRanges()).toEqual([
          [[0, 0], [0, 5]],
          [[0, 11], [0, 13]]
        ])
        expect(editor.getCursorBufferPositions()).toEqual([
          [0, 5]
          [0, 13]
        ])
```

**Comment by jacekkopecky** [comment]
Ah, yes, your issue says its atom/vim-mode#782, so the conflicting one is atom/vim-mode#767.

**Comment by jacekkopecky** [comment]
Yes, I am working on many strands and in vim-mode always submitting PRs from master so there are conflicts, sorry about that. It's great that you're doing integration like this - I really only merge all my PRs in my own integration branch, but not the other outstanding ones by other authors.

**Comment by bronson** [comment]
aha, you changed the test procedure too.  works great now, thanks!!!
