### ISSUE TITLE
Uncaught TypeError: Cannot read property 'word' of null

### ISSUE THREAD

**Issue by jackcasey** [bronson/vim-mode-next#8]
1. position the cursor NOT on a 'word' (ie on a blank line)
2. press `shift-8` to search on word under cursor.

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.2
**Thrown From**: [vim-mode-next](https://github.com/bronson/vim-mode-next) package, v0.57.2
### Stack Trace

Uncaught TypeError: Cannot read property 'word' of null

```
At /Users/jack/.atom/packages/vim-mode-next/lib/motions/search-motion.coffee:96

TypeError: Cannot read property 'word' of null
    at SearchCurrentWord.getCurrentWord (/Users/jack/.atom/packages/vim-mode-next/lib/motions/search-motion.coffee:154:95)
    at SearchCurrentWord.getCurrentWordMatch (/Users/jack/.atom/packages/vim-mode-next/lib/motions/search-motion.coffee:169:25)
    at new SearchCurrentWord (/Users/jack/.atom/packages/vim-mode-next/lib/motions/search-motion.coffee:145:27)
    at registerOperationCommands.search-current-word (/Users/jack/.atom/packages/vim-mode-next/lib/vim-state.coffee:754:20)
    at atom-text-editor.commands.(anonymous function) (/Users/jack/.atom/packages/vim-mode-next/lib/vim-state.coffee:800:41)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
    at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)
```
### Commands

```
     -0:37.7.0 core:cancel (atom-text-editor.editor.mini.is-focused)
  9x -0:37.7.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:29.2.0 vim-mode:search-current-word (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 11x -0:27.8.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:27 vim-mode:search-current-word (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 12x -0:25.2.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 13x -0:21.5.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:20.6.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  2x -0:19.8.0 vim-mode:search-current-word (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
 37x -0:16.4.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:14.9.0 vim-mode:delete-to-last-character-of-line (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:14.3.0 vim-mode:search-current-word (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:13.3.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:13 vim-mode:repeat-search (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:11.4.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  3x -0:10.8.0 vim-mode:search-current-word (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "welcome",
      "symbols-view",
      "linter-rubocop"
    ],
    "destroyEmptyPanes": false
  },
  "vim-mode-next": {
    "useSmartcaseForSearch": true,
    "useClipboardAsDefaultRegister": true
  }
}
```
### Installed Packages

``` coffee
# User
atom-alignment, v0.12.1
atom-ctags, v4.1.4
atom-fuzzy-grep, v0.5.0
atomatigit, v1.5.4
cucumber, v0.5.0
cursor-history, v0.4.17
language-cjsx, v0.3.0
language-diff, v0.3.0
linter, v1.3.4
linter-ruby, v1.0.1
monokai, v0.17.0
spacemacs-evil-keys, v0.0.0
vim-mode-next, v0.57.2
vim-mode-visual-block, v0.2.13
vim-surround, v0.8.0

# Dev
No dev packages
```

**Comment by bronson** [comment]
I've switched to vim-mode-plus.  It's really good -- little chance for vim-mode-next to catch up.  Definitely recommended.
